Omega_Lambda = 0
Omega_fld = 0
Omega_smg = -1
gravity_model = propto_omega
parameters_smg = 30 ,0., 0., 0., 1.
expansion_model = wowa
expansion_smg = 0.67, -0.9, 0.
tuning_dxdy_guess_smg = 1
tuning_index_smg = 1
extra metric transfer functions = y
